### ISSUE TITLE
Why calling to this.refresh() on .result() ?

### ISSUE THREAD

**Issue by jmaister** [jofftiquez/vue-croppie#15]
It was working for me with the last version. Calling this.refresh() on each call to croppie.result() makes my vue-croppie component go to a blank image.

How can I keep the image being cropped ?

Also, a breaking change should bump the middle version according to semver.

**Comment by jofftiquez** [comment]
Hi @jmaister good day! On the `result()` function, you should get the output/cropped image. You need to put that in a variable in order to keep it after the croppie has been `destroyed()`

The `this.result()` is being called to destroy the croppie instance thus avoiding the [#358](https://github.com/Foliotek/Croppie/issues/352) issue on official croppie page.

I will watch out for that breaking changes thank you for notifying me as always.

Did I answer all your questions? Please feel free to join our [gitter chat](https://gitter.im/vue-croppie/Lobby) for future questions :)
