### ISSUE TITLE
EnableResize does not seem to work

### ISSUE THREAD

**Issue by jayhenderson** [jofftiquez/vue-croppie#20]
I've tried setting `:enableResize="true"` inside of my `<vue-croppie>` tag, but it doesn't seem to be doing anything. I was hoping it would enable the resizing functionality shown in one of the examples in [https://foliotek.github.io/Croppie/](url). I might just be doing it incorrectly though. Is this a feature that Vue-Croppie supports?

**Comment by jofftiquez** [comment]
Hello @jayhenderson I'm pretty I've implemented every Croppie features to `vue-croppie`. Regarding your issue, let me just check it on my end. Thank you :)

**Comment by jofftiquez** [comment]
@jayhenderson I think I missed this one. If you search `enableResize` key word on the Croppie's docs, you will not find it in the "Documentation options" part, where I based all the `vue-croppie` options. You will find it in the 3rd example tho. I think that's why I missed it. Anyhow, I will push a new version with the `enableResize` option in it.

**Comment by jofftiquez** [comment]
@jayhenderson I've pushed the new update `@1.3.8` please try it and let me know.

**Comment by jayhenderson** [comment]
Resizing is working, thanks!

**Comment by itxjashankapoor** [comment]
Hi @jofftiquez ,

I'm using following cdn of your library: https://unpkg.com/vue-croppie/dist/vue-croppie.js

Did you also updated the code of this?

**Comment by jofftiquez** [comment]
> Hi @jofftiquez ,
> 
> I'm using following cdn of your library: https://unpkg.com/vue-croppie/dist/vue-croppie.js
> 
> Did you also updated the code of this?

Hello there's no recent update so far aside from the latest.
