### ISSUE TITLE
Boundary should default to size of the container.

### ISSUE THREAD

**Issue by MatthewAry** [jofftiquez/vue-croppie#26]
vue-croppie's prop for boundary defaults to 400x400 px when it should default to the size of the container. See: https://foliotek.github.io/Croppie/#boundary

By having a default boundary size behaviors it breaks complex layouts such as those using flex.

**Comment by jofftiquez** [comment]
@MatthewAry thanks for mentioning this. I'll be working on it.

**Comment by rdomingue** [comment]
Nothing new on this ?

**Comment by jofftiquez** [comment]
@rdomingue sorry it's been quite some time. I will update my timeline on this. Been busy in a while now. :( Thank you for your patience.

**Comment by saeedvz** [comment]
any updates?

**Comment by jofftiquez** [comment]
Hi all, sorry for the delay, I've been very busy lately. Anyways, the fix is now available in `1.3.13`. I removed the default value from the `boundary` props. You just gotta pass a height tho so the layout won't be a mess. You can see that [the demo](https://jofftiquez.github.io/vue-croppie/) is now responsive.

Refer to : 
[L#15](https://github.com/jofftiquez/vue-croppie/blob/8c23e9f55267177349fefc8ac2e51b4f0d673dd9/src/index.js#L15)
[L#76](https://github.com/jofftiquez/vue-croppie/blob/8c23e9f55267177349fefc8ac2e51b4f0d673dd9/src/index.js#L76)
