### ISSUE TITLE
Sample code does not work properly

### ISSUE THREAD

**Issue by ryanhovland** [jofftiquez/vue-croppie#51]
I just tried firing up an instance of vue-croppie with your sample code, but no preview image appears above the slider. I think `.croppie-container` needs an explicit height set. I'm not sure if I'm doing something wrong, but I added the code below and then saw it properly.
```
.croppie-container {
   height: 300px;
   width: 300px;
}
```
p.s. Thanks for your work on this package!

**Comment by jofftiquez** [comment]
Hi @ryanhovland you can actually pass a props called `customClass`. You can define the container's height and width using this. Also, can you try passing this property `:viewport="{ width: 300, height: 300 }"`? Maybe it's what you're looking for. Thanks!

**Comment by ryanhovland** [comment]
@jofftiquez Passing :viewport doesn't fix it. I had to manually define a height (like my code sample above). The `customClass` might work too (didn't try that yet). Either way, just wanted to mention that your sample code isn't working properly as-is. You might want to update it so people don't think the package is broken. 

Thanks again for your work on this. Have a great day!

**Comment by jofftiquez** [comment]
@ryanhovland great! Thank you for notifying me. :) Have a great day too!

**Comment by bmdelacruz** [comment]
When using a custom class, you need to declare the height and the width with an `!important`. Otherwise, they will get overridden by the height and the width that was declared on the `.croppie-container` css style rule which are `height: 100%` and `width: 100%`.

````css
.some-custom-class {
  height: 300px !important;
  width: 300px !important;
}
````

Also, I found out that the __viewport property__ affects the __size of the square that crops the image__ not the size of the croppie container.
